name 'ps_watcher'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures ps_watcher'
long_description 'Installs/Configures ps_watcher'
version '0.1.0'
